name: hello-skyline
image: hello-skyline
slack: pb-s-maldivian-mers
skip_production_deploy: true
staging:
  environment:
    RACK_ENV: staging
    RAILS_ENV: staging
deployables:
  web:
    type: web
    port: 3000
    command: "bundle exec rails server -p 3000 -b 0.0.0.0"
    health_check_path: "/"
    staging:
      host: "hello-skyline.staging-ezcater.com"
      replicas: 1 # how many containers to run in kubernetes

tests:
  primary:
    - name: hello-skyline
      build: .
  steps:
    - run:
        test: bundle
        command: bundle install --jobs=4 --retry=3
    - run:
        test: rspec
        command: bundle exec rspec
